module.exports = [
"Advertising",
"Allowance on eligible capital property",
"Bad debts",
"Business start-up costs",
"Business taxes, fees, licences, dues, memberships, and subscriptions",
"Business-use-of-home expenses",
"Capital cost allowance",
"Current or capital expenses",
"Delivery, freight, and express",
"Fuel costs",
"Insurance",
"Interest",
"Legal, accounting, and other professional fees",
"Maintenance and repairs",
"Management and administration fees",
"Meals and entertainment",
"Motor vehicle expenses (automobile)",
"Office expenses",
"Prepaid expenses",
"Property taxes",
"Rent",
"Salaries, wages, and benefits",
"Supplies",
"Telephone and utilities",
"Travel",
"Other expenses",
]
